spool '09_vysledky_dotazu.txt';
--last_update_time > create_time
INSERT INTO "A_COMPUTER" (COMPUTER_ID, BPCS_SESSIONS, COMMENTS, CREATE_TIME, GUARANTEES, INVENTORY_NUMBER, LAST_UPDATE_TIME, MAC_ADDRESS, COMPUTER_NAME, SERIAL_NUMBER, COMPUTER_BRAND_ID, COMPUTER_PARAMETERS_ID, OS_ID, USER_ID) VALUES ('9999', 'BPCS_1_FRYCZ-9999, BPCS_2_FRYCZ-9998, BPCS_3_FRYCZ-9998', 'Comment', TO_DATE('06.06.1930', 'DD.MM.YYYY'), TO_DATE('06.06.1941', 'DD.MM.YYYY'), 'FRYCZ - 9998/83707SW:A2:F5:8B:FE:41', TO_DATE('12.05.1920', 'DD.MM.YYYY'), 'SW:A2:F5:8B:FE:41', 'FRYCZ-9998', 'OACRPJPH9IW0K25EX', '87', '1199', '1', '1328');

--guarantees > create_time
INSERT INTO "A_COMPUTER" (COMPUTER_ID, BPCS_SESSIONS, COMMENTS, CREATE_TIME, GUARANTEES, INVENTORY_NUMBER, LAST_UPDATE_TIME, MAC_ADDRESS, COMPUTER_NAME, SERIAL_NUMBER, COMPUTER_BRAND_ID, COMPUTER_PARAMETERS_ID, OS_ID, USER_ID) VALUES ('9999', 'BPCS_1_FRYCZ-9999, BPCS_2_FRYCZ-9998, BPCS_3_FRYCZ-9998', 'Comment', TO_DATE('06.06.1930', 'DD.MM.YYYY'), TO_DATE('06.06.1920', 'DD.MM.YYYY'), 'FRYCZ - 9998/83707SW:A2:F5:8B:FE:41', TO_DATE('12.05.1940', 'DD.MM.YYYY'), 'SW:A2:F5:8B:FE:41', 'FRYCZ-9998', 'OACRPJPH9IW0K25EX', '87', '1199', '1', '1328');

--mac_address not null
INSERT INTO "A_COMPUTER" (COMPUTER_ID, BPCS_SESSIONS, COMMENTS, CREATE_TIME, GUARANTEES, INVENTORY_NUMBER, LAST_UPDATE_TIME, COMPUTER_NAME, SERIAL_NUMBER, COMPUTER_BRAND_ID, COMPUTER_PARAMETERS_ID, OS_ID, USER_ID) VALUES ('9999', 'BPCS_1_FRYCZ-9999, BPCS_2_FRYCZ-9998, BPCS_3_FRYCZ-9998', 'Comment', TO_DATE('06.06.1930', 'DD.MM.YYYY'), TO_DATE('06.06.1939', 'DD.MM.YYYY'), 'FRYCZ - 9998/83707SW:A2:F5:8B:FE:41', TO_DATE('12.05.1940', 'DD.MM.YYYY'), 'SW:A2:F5:8B:FE:41', 'FRYCZ-9998', '87', '1199', '1', '1328');

--computer_name not null
INSERT INTO "A_COMPUTER" (COMPUTER_ID, BPCS_SESSIONS, COMMENTS, CREATE_TIME, GUARANTEES, INVENTORY_NUMBER, LAST_UPDATE_TIME, MAC_ADDRESS, SERIAL_NUMBER, COMPUTER_BRAND_ID, COMPUTER_PARAMETERS_ID, OS_ID, USER_ID) VALUES ('9999', 'BPCS_1_FRYCZ-9999, BPCS_2_FRYCZ-9998, BPCS_3_FRYCZ-9998', 'Comment', TO_DATE('06.06.1930', 'DD.MM.YYYY'), TO_DATE('06.06.1939', 'DD.MM.YYYY'), 'FRYCZ - 9998/83707SW:A2:F5:8B:FE:41', TO_DATE('12.05.1940', 'DD.MM.YYYY'), 'SW:A2:F5:8B:FE:41', 'OACRPJPH9IW0K25EX', '87', '1199', '1', '1328');

--user_first_name not null
INSERT INTO "A_USER" (USER_ID, USER_LAST_NAME, USER_ROLE, USER_PASSWORD, USER_LOGIN, USER_EMAIL_ADDRESS) VALUES ('2001', 'Emeney', 'Office', '810YZM', 'EmenJo1', 'jemeneyrr@sina.com.cn');

--user_last_name not null
INSERT INTO "A_USER" (USER_ID, USER_FIRST_NAME, USER_ROLE, USER_PASSWORD, USER_LOGIN, USER_EMAIL_ADDRESS) VALUES ('2001', 'Joyann', 'Office', '810YZM', 'EmenJo1', 'jemeneyrr@sina.com.cn');

--user_email_address
INSERT INTO "A_USER" (USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_ROLE, USER_PASSWORD, USER_LOGIN, USER_EMAIL_ADDRESS) VALUES ('2001', 'Joyann', 'Emeney', 'Office', '810YZM', 'EmenJo1', 'jemeneyrrsina.com.cn');
INSERT INTO "A_USER" (USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_ROLE, USER_PASSWORD, USER_LOGIN, USER_EMAIL_ADDRESS) VALUES ('2001', 'Joyann', 'Emeney', 'Office', '810YZM', 'EmenJo1', 'jemeneyr@rsina@com.cn');

--user_password not null
INSERT INTO "A_USER" (USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_ROLE, USER_LOGIN, USER_EMAIL_ADDRESS) VALUES ('2001', 'Joyann', 'Emeney', 'Office', 'EmenJo1', 'jemeneyrr@sina.com.cn');

--user_login not null
INSERT INTO "A_USER" (USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_ROLE, USER_PASSWORD, USER_EMAIL_ADDRESS) VALUES ('2001', 'Joyann', 'Emeney', 'Office', '810YZM', 'jemeneyrr@sina.com.cn');

--user_role not null
INSERT INTO "A_USER" (USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_PASSWORD, USER_LOGIN, USER_EMAIL_ADDRESS) VALUES ('2001', 'Joyann', 'Emeney', '810YZM', 'EmenJo1', 'jemeneyrr1@sina.com.cn');

--hdd > 0
INSERT INTO "A_COMPUTER_PARAMETERS" (COMPUTER_PARAMETERS_ID, EXTERNAME_GPU, OPTICAL_DISK_DRIVE, HDD, PROCESSOR, RAM) VALUES ('1200', '0', '1', '-1', 'itanium', '512');

--ram > 0
INSERT INTO "A_COMPUTER_PARAMETERS" (COMPUTER_PARAMETERS_ID, EXTERNAME_GPU, OPTICAL_DISK_DRIVE, HDD, PROCESSOR, RAM) VALUES ('1200', '0', '1', '256', 'itanium', '-1');

--extername_GPU not null
INSERT INTO "A_COMPUTER_PARAMETERS" (COMPUTER_PARAMETERS_ID, OPTICAL_DISK_DRIVE, HDD, PROCESSOR, RAM) VALUES ('1200', '1', '256', 'itanium', '512');

--optical_disk_drive not null
INSERT INTO "A_COMPUTER_PARAMETERS" (COMPUTER_PARAMETERS_ID, EXTERNAME_GPU, HDD, PROCESSOR, RAM) VALUES ('1200', '0', '256', 'itanium', '512');

--processor not null
INSERT INTO "A_COMPUTER_PARAMETERS" (COMPUTER_PARAMETERS_ID, EXTERNAME_GPU, OPTICAL_DISK_DRIVE, HDD, RAM) VALUES ('1200', '0', '1', '256', '-1');

--os_version > 0
INSERT INTO "A_OS" (OS_ID, OS_NAME, OS_VERSION) VALUES ('40', 'HoneyWell2', '-1');

--os_name not null
INSERT INTO "A_OS" (OS_ID, OS_VERSION) VALUES ('40', '64');

--Pokud ma novy pocitac vyplneneho vyrobce a model (COMPUTER_BRAND), pak jeho SERIAL_NUMBER nesmi byt NULL
INSERT INTO "A_COMPUTER" (COMPUTER_ID, BPCS_SESSIONS, COMMENTS, CREATE_TIME, GUARANTEES, INVENTORY_NUMBER, LAST_UPDATE_TIME, MAC_ADDRESS, COMPUTER_NAME, COMPUTER_BRAND_ID, COMPUTER_PARAMETERS_ID, OS_ID, USER_ID) VALUES ('10000', 'BPCS_1_FRYCZ-9999, BPCS_2_FRYCZ-9998, BPCS_3_FRYCZ-9998', 'comment', TO_DATE('06.06.1939', 'DD.MM.YYYY'), TO_DATE('06.06.1941', 'DD.MM.YYYY'), 'FRYCZ - 9998/83707SW:A2:F5:8B:FE:411', TO_DATE('12.05.2019', 'DD.MM.YYYY'), 'SW:A2:F5:8B:FE:411', 'FRYCZ-9999', '87', '1199', '1', '1328');
spool off;