DROP TABLE A_COMPUTER;
DROP TABLE A_COMPUTER_BRAND;
DROP TABLE A_USER;
DROP TABLE A_COMPUTER_PARAMETERS;
DROP TABLE A_OS;

DROP TABLE OBJ_A_COMPUTER;
DROP TABLE OBJ_A_COMPUTER_BRAND;
DROP TABLE OBJ_A_USER;
DROP TABLE OBJ_A_COMPUTER_PARAMETERS;
DROP TABLE OBJ_A_OS;

DROP SEQUENCE seq_OS;
DROP SEQUENCE seq_Brand;
DROP SEQUENCE seq_Parameters;
DROP SEQUENCE seq_User;
DROP SEQUENCE seq_Computer;

DROP PROCEDURE hr.kontrola_brand;
DROP PACKAGE pocitacova_databaze_api;